# Generated by Django 3.0.9 on 2020-08-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Genre', models.CharField(max_length=150)),
            ],
        ),
    ]
