# Generated by Django 3.0.9 on 2020-08-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Genre',
        ),
    ]
