# Generated by Django 3.0.9 on 2020-08-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Tickets', models.CharField(max_length=200)),
                ('Seat_Type', models.CharField(max_length=200)),
                ('Theatre', models.CharField(max_length=200)),
                ('Customer_Name', models.CharField(max_length=200)),
                ('Email_ID', models.CharField(max_length=200)),
                ('Movies', models.CharField(max_length=200)),
            ],
        ),
    ]
